name: PR

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

jobs:

  lint_build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    
    - name: Vendor
      run: go mod vendor

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-go-installation: true
        version: latest
        args: --timeout 3m --verbose

    - name: Build
      run: go build -v cmd/grafana-app-sdk/*.go

    - name: Test
      run: go test -v ./...