name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
    # make test
    - name: Test
      run: go test -v ./...
  integration-test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
    # Install the CLI
    - name: Install the CLI
      run: cd cmd/grafana-app-sdk && go install && cd -
    # Generate code
    - name: Generate code from test file
      run: | 
        mkdir -p codegen-tests && cd codegen-tests
        grafana-app-sdk project init codegen-tests
        cp ../codegen/cuekind/testing/customkind.cue kinds/customkind.cue
        grafana-app-sdk generate
