name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
    # make test
    - name: Test
      run: go test -v ./...
  integration-test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"
    # Install the CLI
    - name: Install the CLI
      run: cd cmd/grafana-app-sdk && go install && cd -
    # Generate code
    - name: Copy test CUE files
      run: | 
        mkdir -p codegen-tests && cd codegen-tests
        grafana-app-sdk project init codegen-tests
        cp ../codegen/cuekind/testing/*.cue kinds/
    - name: Generate code
      run: | 
        cd codegen-tests
        grafana-app-sdk generate --kindgrouping=kind --gogenpath=pkg/gen1 --tsgenpath=ts/gen1
        mkdir -p cmp/go1 && cp -R ../codegen/testing/golden_generated/go/groupbykind/* cmp/go1
        find ./cmp/go1 -iname '*.txt' -exec bash -c 'mv -- "$1" "${1%.txt}"' bash {} \;
        diff pkg/generated/resource/customkind cmp/customkind > diff.txt
        echo "'grafana-app-sdk generate --kindgrouping=kind' golang output diff from golden:"
        cat diff.txt
        sed -i '/^Common subdirectories/d' diff.txt
        difflines=$(wc -l diff.txt | awk '{ print $1 }')
        echo "GoGroupByKindDiff=${difflines}" >> $GITHUB_ENV
    - name: Compare generated go code
      if: ${{ env.GoGroupByKindDiff != '0' }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Code generated by `grafana-app-sdk generate` does not match golden files in `codegen/testing/golden_generated` (diff was ${{ env.GoGrouByKindDiff }} lines long, check output of previous step)')
    - name: Compare generated TypeScript code
      run: | 
        cd codegen-tests
        mkdir -p cmd/ts1 && cp -R ../codegen/testing/golden_generated/typescript/versioned/* cmp/ts1
        find ./cmp/ts1 -iname '*.txt' -exec bash -c 'mv -- "$1" "${1%.txt}"' bash {} \;
        diff ts/gen1 cmp/ts1 > diff.txt
        echo "'grafana-app-sdk generate --kindgrouping=kind' TypeScript output diff from golden:"
        cat diff.txt
        sed -i '/^Common subdirectories/d' diff.txt
        [ $(wc -l diff.txt | awk '{ print $1 }') -gt 0 ] && exit 1
